apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: aws-openvpn-server
  annotations:
    github.com/project-slug: nesport/aws-openvpn-server
spec:
  type: service
  lifecycle: experimental
  owner: team-c
  providesApis:
    - petstore1
